<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXt4bf7o\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXt4bf7o/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerXt4bf7o.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerXt4bf7o\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerXt4bf7o\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Xt4bf7o',
    'container.build_id' => '1380826e',
    'container.build_time' => 1534055777,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerXt4bf7o');
